/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package de_012_oop;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author FPT
 */
public class FormQuanLyPhuongTien extends javax.swing.JFrame {

    /**
     * Creates new form FormQuanLyPhuongTien
     */
    ArrayList<PhuongTien> listPhuongTien = new ArrayList<>();
    public FormQuanLyPhuongTien() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Quản Lý Phương Tiện");
        String chon = cbbLoaiPhuongTien.getSelectedItem().toString();
        if(chon.equals("Ô Tô")){
            lblThuocTinh1.setText("Số Chỗ Ngồi:");
            lblThuocTinh2.setText("Kiểu Động Cơ:");
        }
        else if(chon.equals("Xe Máy")){
            lblThuocTinh1.setText("Dung Tích Bình Xăng:");
            lblThuocTinh2.setText("Công Suất:");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSoKhung = new javax.swing.JTextField();
        txtNhanHieu = new javax.swing.JTextField();
        txtGiaBan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbbLoaiPhuongTien = new javax.swing.JComboBox<>();
        lblThuocTinh1 = new javax.swing.JLabel();
        lblThuocTinh2 = new javax.swing.JLabel();
        txtThuocTinh1 = new javax.swing.JTextField();
        txtThuocTinh2 = new javax.swing.JTextField();
        btnLuu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ PHƯƠNG TIỆN");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Số Khung:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nhãn Hiệu:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Giá Bán:");

        txtSoKhung.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtNhanHieu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtGiaBan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Chọn Loại Phương Tiện:");

        cbbLoaiPhuongTien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbbLoaiPhuongTien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Xe Máy", "Ô Tô" }));
        cbbLoaiPhuongTien.setName(""); // NOI18N
        cbbLoaiPhuongTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbLoaiPhuongTienActionPerformed(evt);
            }
        });

        lblThuocTinh1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblThuocTinh1.setText("Dung Tích Bình Xăng:");

        lblThuocTinh2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblThuocTinh2.setText("Công Suất:");

        txtThuocTinh1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtThuocTinh2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnLuu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNhanHieu, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSoKhung, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbbLoaiPhuongTien, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblThuocTinh1)
                            .addComponent(lblThuocTinh2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtThuocTinh2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtThuocTinh1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnLuu))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbbLoaiPhuongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSoKhung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblThuocTinh1)
                    .addComponent(txtThuocTinh1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNhanHieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblThuocTinh2)
                    .addComponent(txtThuocTinh2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(btnLuu)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbbLoaiPhuongTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbLoaiPhuongTienActionPerformed
        // TODO add your handling code here:
        String chon = cbbLoaiPhuongTien.getSelectedItem().toString();
        if(chon.equals("Ô Tô")){
            lblThuocTinh1.setText("Số Chỗ Ngồi:");
            lblThuocTinh2.setText("Kiểu Động Cơ:");
        }
        else if(chon.equals("Xe Máy")){
            lblThuocTinh1.setText("Dung Tích Bình Xăng:");
            lblThuocTinh2.setText("Công Suất:");
        }
    }//GEN-LAST:event_cbbLoaiPhuongTienActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        String soKhung = txtSoKhung.getText();
        String nhanHieu = txtNhanHieu.getText();
        double giaBan = Double.parseDouble(txtGiaBan.getText());
        String chon = cbbLoaiPhuongTien.getSelectedItem().toString();
        if(giaBan < 1000000){
            JOptionPane.showMessageDialog(this, "Giá Bán Bắt Buộc Phải Trên 1.000.000");
            return;
            
        }
         
        try {
             giaBan = Double.parseDouble(txtGiaBan.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Vui Lòng Nhập Số!");;
            return;
            
        }
        if(chon.equals("Ô Tô")){
            int soChoNgoi = Integer.parseInt(txtThuocTinh1.getText());
            String kieuDongCo = txtThuocTinh2.getText();
            Oto oto = new Oto(soChoNgoi, kieuDongCo, soKhung, nhanHieu, giaBan);
            listPhuongTien.add(oto);
            System.out.println(oto.hienThiThongTin());
        }
        else if(chon.equals("Xe Máy")){
            String dungTichBinhXang = txtThuocTinh1.getText();
            String congSuat = txtThuocTinh2.getText();
            XeMay xm = new XeMay(dungTichBinhXang, congSuat, soKhung, nhanHieu, giaBan);
            listPhuongTien.add(xm);
            System.out.println(xm.hienThiThongTin());
        }
        
    }//GEN-LAST:event_btnLuuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormQuanLyPhuongTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormQuanLyPhuongTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormQuanLyPhuongTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormQuanLyPhuongTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormQuanLyPhuongTien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuu;
    private javax.swing.JComboBox<String> cbbLoaiPhuongTien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblThuocTinh1;
    private javax.swing.JLabel lblThuocTinh2;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtNhanHieu;
    private javax.swing.JTextField txtSoKhung;
    private javax.swing.JTextField txtThuocTinh1;
    private javax.swing.JTextField txtThuocTinh2;
    // End of variables declaration//GEN-END:variables
}
